# Generated by Django 4.1.4 on 2022-12-14 07:17

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок новостей')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='Заголовок новостей')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='Заголовок новостей')),
                ('img', models.ImageField(upload_to='', verbose_name='Фото картинок')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание новостей')),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание новостей')),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание новостей')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('slug_ru', models.SlugField(null=True, unique=True)),
                ('slug_en', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
